pipeline {
 
    agent any

    stages {

        stage('mark build-automation scripts as executable') {

            steps {

                sh 'chmod +x ./build-automation/*.sh'                        

            }

        }
        
        stage('build docker image from Dockerfile') {

            steps {

                sh 'cd build-automation;./build-pass-1-build-docker-image-from-dockerfile.sh'

            }

        }

        stage('push docker image to softwareshinobi DockerHub') {

            steps {

                sh 'cd build-automation;./build-pass-2-push-docker-image-to-dockerhub.sh'

            }

        }
        
        stage('pemove docker image from local repository') {

            steps {

                sh 'cd build-automation;./build-pass-3-remove-docker-image-from-local.sh'

            }

        }              
              
    }

}
